"""Generate INT8 matrix multiply test vectors for the RTL team (sizes 4, 8, 16)."""
import os
import numpy as np

OUT_DIR = "test_vectors"


def save_int8_hex(matrix: np.ndarray, path: str) -> None:
    flat = matrix.astype(np.int8).flatten()
    with open(path, "w") as f:
        for v in flat:
            f.write(f"{np.uint8(v):02x}\n")


def save_int32_hex(matrix: np.ndarray, path: str) -> None:
    flat = matrix.astype(np.int32).flatten()
    with open(path, "w") as f:
        for v in flat:
            f.write(f"{np.uint32(v):08x}\n")


def save_tile(A: np.ndarray, B: np.ndarray, base: str) -> None:
    C = A.astype(np.int32) @ B.astype(np.int32)
    save_int8_hex(A, base + "_A.hex")
    save_int8_hex(B, base + "_B.hex")
    save_int32_hex(C, base + "_C_expected.hex")


def read_int8(path: str, n: int) -> np.ndarray:
    vals = [int(line.strip(), 16) for line in open(path)]
    return np.array(vals, dtype=np.uint8).view(np.int8).reshape(n, n)


def read_int32(path: str, n: int) -> np.ndarray:
    vals = [int(line.strip(), 16) for line in open(path)]
    return np.array(vals, dtype=np.uint32).view(np.int32).reshape(n, n)


def verify_size(size: int) -> bool:
    """Read back tile_00 for the given size and check A@B == C_expected."""
    base = os.path.join(OUT_DIR, f"size_{size}", "random", "tile_00")
    A = read_int8(base + "_A.hex", size)
    B = read_int8(base + "_B.hex", size)
    C = read_int32(base + "_C_expected.hex", size)
    C_ref = A.astype(np.int32) @ B.astype(np.int32)
    return np.array_equal(C, C_ref)


def write_readme(sizes: list) -> None:
    size_rows = "\n".join(
        f"| `size_{n}/` | {n}×{n} systolic array; 10 random tiles + 3 edge cases |"
        for n in sizes
    )
    verilog_examples = "\n\n".join(
        f"// {n}×{n} tile\n"
        f'logic signed [7:0]  A_{n} [0:{n*n-1}];\n'
        f'logic signed [7:0]  B_{n} [0:{n*n-1}];\n'
        f'logic signed [31:0] C_{n} [0:{n*n-1}];\n'
        f'initial begin\n'
        f'    $readmemh("size_{n}/random/tile_00_A.hex",          A_{n});\n'
        f'    $readmemh("size_{n}/random/tile_00_B.hex",          B_{n});\n'
        f'    $readmemh("size_{n}/random/tile_00_C_expected.hex", C_{n});\n'
        f'end'
        for n in sizes
    )
    readme = f"""\
# Test Vectors for INT8 Matrix Multiply

Generated by `generate_test_vectors.py` using `np.random.seed(42)`.

## Size subfolders

| Folder | Contents |
|--------|----------|
{size_rows}

Each size folder contains two subfolders:
- `random/` — 10 random tiles: `tile_00_*` … `tile_09_*`
- `edge/`   — 3 edge cases: `zeros_*`, `identity_*`, `maxval_*`

## File format

For an N×N tile there are three files:

| Suffix | Type | Lines | Chars/line |
|--------|------|-------|------------|
| `_A.hex` | INT8 | N² | 2 (two's complement) |
| `_B.hex` | INT8 | N² | 2 (two's complement) |
| `_C_expected.hex` | INT32 | N² | 8 (two's complement) |

Values are stored in **row-major** order (row 0 first).

Examples: `-1` (INT8) → `ff`; `-128` → `80`; `127` → `7f`; `-1` (INT32) → `ffffffff`

## Edge cases (all sizes)

| File prefix | Description |
|-------------|-------------|
| `zeros` | All-zeros A and B → all-zeros C |
| `identity` | Identity × Identity = Identity |
| `maxval` | All-127 A and B → INT32 overflow stress test |

## Verilog `$readmemh` usage

```verilog
{verilog_examples}
```

Row `r`, column `c` is at index `r*N + c`.
"""
    with open(os.path.join(OUT_DIR, "README.md"), "w") as f:
        f.write(readme)


def main():
    np.random.seed(42)

    sizes = [4, 8, 16]

    for size in sizes:
        rand_dir = os.path.join(OUT_DIR, f"size_{size}", "random")
        edge_dir = os.path.join(OUT_DIR, f"size_{size}", "edge")
        os.makedirs(rand_dir, exist_ok=True)
        os.makedirs(edge_dir, exist_ok=True)

        # 10 random tiles
        for i in range(10):
            A = np.random.randint(-128, 128, size=(size, size), dtype=np.int8)
            B = np.random.randint(-128, 128, size=(size, size), dtype=np.int8)
            save_tile(A, B, os.path.join(rand_dir, f"tile_{i:02d}"))

        # Edge case: all-zeros
        z = np.zeros((size, size), dtype=np.int8)
        save_tile(z, z, os.path.join(edge_dir, "zeros"))

        # Edge case: identity matrix
        eye = np.eye(size, dtype=np.int8)
        save_tile(eye, eye, os.path.join(edge_dir, "identity"))

        # Edge case: all-127 (near-overflow stress test)
        maxval = np.full((size, size), 127, dtype=np.int8)
        save_tile(maxval, maxval, os.path.join(edge_dir, "maxval"))

        print(f"  size_{size}: generated 10 random + 3 edge tiles")

    write_readme(sizes)
    print(f"README written to {OUT_DIR}/README.md")

    print("\nVerification:")
    all_pass = True
    for size in sizes:
        ok = verify_size(size)
        status = "PASS" if ok else "FAIL"
        print(f"  size_{size}: {status}")
        if not ok:
            all_pass = False

    print("\nOverall:", "PASS" if all_pass else "FAIL")


if __name__ == "__main__":
    main()
